### ISSUE TITLE
Not an issue, but

### ISSUE THREAD

**Issue by Avnsx** [behnambm/nordvpn-checker#4]
would be very happy if you re-wrote this for windows 👍

**Comment by behnambm** [comment]
Hi
I'm not using Windows, but I think you can use this script through CMD 

this might be useful
https://support.nordvpn.com/Connectivity/Windows/1350897482/Connect-to-NordVPN-app-on-Windows-using-the-Command-Prompt.htm

If that doesn't work you should wait because I am busy with my university stuff, or you can work on this if you want :)
